name: CI-CD - Build Docker Images and Deploy to DockerHub

on: 
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

jobs:
  docker-build:
    name: Build, Scan and Push Docker Image
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ vars.DOCKER_USERNAME }}/weight-converter
          tags: |
            type=semver,pattern={{major}}.{{minor}}
            
      - name: Build docker image (load into local Docker)
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./app/Dockerfile

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.meta.outputs.tags }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: CRITICAL,HIGH

      - name: Update Kubernetes manifest (only on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          IMAGE=$(echo "${{ steps.meta.outputs.tags }}" | cut -d',' -f1)
          sed -i "s|image: .*|image: $IMAGE|g" k8s/deployment.yml

      - name: Commit and push changes
        if: startsWith(github.ref, 'refs/tags/v')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update image to ${{ steps.meta.outputs.tags }}"
          file_pattern: k8s/deployment.yml
